// Generated by CoffeeScript 1.10.0
(function() {
  var DealTable, Deck, Game, GameApplicationService, Player;

  Game = require('../domain/game');

  Player = require('../domain/player');

  DealTable = require('../domain/dealTable');

  Deck = require('../domain/deck');

  module.exports = GameApplicationService = (function() {
    function GameApplicationService() {}

    GameApplicationService.prototype.createNewGame = function(numberOfPlayers) {
      var dealTable, deck, i, j, players, ref;
      dealTable = new DealTable();
      deck = new Deck();
      players = [];
      for (i = j = 1, ref = numberOfPlayers; 1 <= ref ? j <= ref : j >= ref; i = 1 <= ref ? ++j : --j) {
        players.push(new Player(i));
      }
      return new Game(dealTable, deck, players);
    };

    return GameApplicationService;

  })();

}).call(this);
