// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = Object.freeze({
    six: 6,
    seven: 7,
    eight: 8,
    nine: 9,
    ten: 10,
    B: 11,
    D: 12,
    K: 13,
    A: 14
  });

}).call(this);
