// Generated by CoffeeScript 1.10.0
(function() {
  var Card;

  module.exports = Card = (function() {
    function Card(number, suit) {
      this.number = number;
      this.suit = suit;
    }

    return Card;

  })();

}).call(this);
