// Generated by CoffeeScript 1.10.0
(function() {
  var DealTable;

  module.exports = DealTable = (function() {
    function DealTable() {
      this.ground = [];
      this.pile = [];
      this.trump = null;
    }

    return DealTable;

  })();

}).call(this);
