// Generated by CoffeeScript 1.10.0
(function() {
  var Card, CardNumber, Deck;

  Card = require('./card');

  CardNumber = require('./cardNumber');

  module.exports = Deck = (function() {
    function Deck() {
      this._suits = ['Hearts', 'Spades', 'Clubs', 'Diamonds'];
      this.cards = [];
      this._createCards();
    }

    Deck.prototype._createCards = function() {
      var i, k, len, name, ref, results, suit;
      ref = this._suits;
      results = [];
      for (k = 0, len = ref.length; k < len; k++) {
        suit = ref[k];
        results.push((function() {
          var l, results1;
          results1 = [];
          for (i = l = 6; l <= 14; i = ++l) {
            name = i;
            if (i === 6) {
              name = CardNumber.six;
            }
            if (i === 7) {
              name = CardNumber.seven;
            }
            if (i === 8) {
              name = CardNumber.eight;
            }
            if (i === 9) {
              name = CardNumber.nine;
            }
            if (i === 10) {
              name = CardNumber.ten;
            }
            if (i === 11) {
              name = CardNumber.B;
            }
            if (i === 12) {
              name = CardNumber.D;
            }
            if (i === 13) {
              name = CardNumber.K;
            }
            if (i === 14) {
              name = CardNumber.A;
            }
            results1.push(this.cards.push(new Card(name, suit)));
          }
          return results1;
        }).call(this));
      }
      return results;
    };

    Deck.prototype.shuffle = function() {
      var i, j, k, ref, results, temp;
      results = [];
      for (i = k = ref = this.cards.length - 1; k >= 0; i = k += -1) {
        j = Math.floor(Math.random() * (i + 1));
        temp = this.cards[i];
        this.cards[i] = this.cards[j];
        results.push(this.cards[j] = temp);
      }
      return results;
    };

    return Deck;

  })();

}).call(this);
