// Generated by CoffeeScript 1.10.0
(function() {
  var Card, Deck;

  Card = require('../../src/domain/card');

  module.exports = Deck = (function() {
    function Deck() {
      this.suits = ['Heart', 'Spades', 'Clubs', 'Diamonds'];
      this.cards = [];
      this._createCards();
    }

    Deck.prototype._createCards = function() {
      var i, j, len, name, ref, results, suit;
      ref = this.suits;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        suit = ref[j];
        results.push((function() {
          var k, results1;
          results1 = [];
          for (i = k = 6; k <= 14; i = ++k) {
            name = i;
            if (i === 11) {
              name = 'B';
            }
            if (i === 12) {
              name = 'D';
            }
            if (i === 13) {
              name = 'K';
            }
            if (i === 14) {
              name = 'A';
            }
            results1.push(this.cards.push(new Card(name, suit)));
          }
          return results1;
        }).call(this));
      }
      return results;
    };

    return Deck;

  })();

}).call(this);
