// Generated by CoffeeScript 1.10.0
(function() {
  var Card, CardNumber, Deck, Suit;

  Card = require('./card');

  Suit = require('./suit');

  CardNumber = require('./cardNumber');

  module.exports = Deck = (function() {
    function Deck() {
      this._suits = ['Hearts', 'Spades', 'Clubs', 'Diamonds'];
      this.cards = [];
      this._createCards();
    }

    Deck.prototype._createCards = function() {
      var i, j, len, name, ref, results, suit;
      ref = this._suits;
      results = [];
      for (j = 0, len = ref.length; j < len; j++) {
        suit = ref[j];
        results.push((function() {
          var k, results1;
          results1 = [];
          for (i = k = 6; k <= 14; i = ++k) {
            name = i;
            if (i === 6) {
              name = CardNumber.six;
            }
            if (i === 7) {
              name = CardNumber.seven;
            }
            if (i === 8) {
              name = CardNumber.eight;
            }
            if (i === 9) {
              name = CardNumber.nine;
            }
            if (i === 10) {
              name = CardNumber.ten;
            }
            if (i === 11) {
              name = CardNumber.B;
            }
            if (i === 12) {
              name = CardNumber.D;
            }
            if (i === 13) {
              name = CardNumber.K;
            }
            if (i === 14) {
              name = CardNumber.A;
            }
            results1.push(this.cards.push(new Card(name, suit)));
          }
          return results1;
        }).call(this));
      }
      return results;
    };

    return Deck;

  })();

}).call(this);
