// Generated by CoffeeScript 1.10.0
(function() {
  var Game;

  module.exports = Game = (function() {
    function Game(dealTable, deck1, players1) {
      this.dealTable = dealTable;
      this.deck = deck1;
      this.players = players1;
      this.currentTurn = [];
      this.started = new Date();
      this.finished = new Date();
      this.inProgress = true;
      this.winner = null;
      this._createNewGame();
    }

    Game.prototype._createNewGame = function() {
      var j, len, player, ref;
      ref = this.players;
      for (j = 0, len = ref.length; j < len; j++) {
        player = ref[j];
        this.currentTurn.push(player.id);
      }
      this._dealPlayers(this.deck, this.players);
      return this._dealTable(this.deck, this.dealTable);
    };

    Game.prototype._dealPlayers = function(deck, players) {
      var i, j, len, player, results;
      results = [];
      for (j = 0, len = players.length; j < len; j++) {
        player = players[j];
        results.push((function() {
          var k, results1;
          results1 = [];
          for (i = k = 1; k <= 6; i = ++k) {
            results1.push(player.hand.push(deck.cards.shift()));
          }
          return results1;
        })());
      }
      return results;
    };

    Game.prototype._dealTable = function(deck, table) {
      return table.trump = deck.cards.shift();
    };

    return Game;

  })();

}).call(this);
