// Generated by CoffeeScript 1.10.0
(function() {
  var Player;

  module.exports = Player = (function() {
    function Player(id) {
      this.id = id;
      this.hand = [];
    }

    return Player;

  })();

}).call(this);
